### PR TITLE
Draft of new layout

### PR DESCRIPTION
**Pull request by ontracrous**
I just finished creating the initial structure of the new software using the framework I set up.

Before I started adding the existing software into the framework I put everything in the folder `/old`. Most of the folders I've already moved to the new layout such as `db_helper`, `resources`, `donations`, ` assets`.
I wasn't able to figure out what to do with `resources`, `donations`, so they're not implemented yet in the software.

For the rest of the software that's in `dash_app.py` I've gone through I think most of the `def`s. Every `def` I incorporated in the framework has `# DONE` above it to mark it implemented.

I added `calculations.py` and `database.py` in `/data`. 
In `calculations.py` calculations are performed that were previously done in the `def`s to plot stuff. That's now more generalised with data being filtered in 1 location.

In `database.py` we interface with the database and a call-back can request the following `dataframes`:
- unfiltered
- filtered (should be default)
- statistics

I wanted to do this on a data/database level to keep a proper multi-levelled structure.
If we want a new type of dataframe we should add it in `/data/database.py` and have some calculations  in `/data/calculations.py`

Furthermore, I've changed the output `id`s of the callbacks to make it easier to read what the `id` is used for.
And I've added all the call-backs/plots to 7 different views at the moment. Just to have everything implement. Once everything's running we can switch stuff around.
All the call-backs and views should be linked properly.

I added a couple of `# TODO:`s with stuff that still needs to be done.

Feel free to change things around and add stuff. I did look at the database stuff and implemented it, but I'm unsure if it works so do look at that.

TODO:
- Empty the `/old` folder and incorporate everything in the new structure, most of `dash_app.py` should be done already
- Check if the database is linked correctly and it works
- Add datepicker components
- Testing
- Other TODOs noted in the software

I haven't come around to testing it yet, I'm too tired right now to do anything and I'm going to bed.

### CODE REVIEW

**Comment by ontracrous** [comment]
The new data coming from the ign place isn't incorporated in this software btw, so that has to be added as well.
Whoops

**Comment by Anonymous5726221** [comment]
I'll need some time to review all that.
The data ingestion part is separate from this repo so no worries about IGN. In fact I might end up removing the refresh_db tool really, that's something I use localy to do some fixes on the db.

**Comment by Anonymous5726221** [comment]
Ok got it to run, needed to replace `app = None` to an empty dash instance `app = dash.Dash()`

**Comment by ontracrous** [comment]
Looking at it right now while I'm actually supposed to do work instead...
Looks like the tables are giving issues. Likely because they're not an actual callback. And that somehow messes things up.

We could comment it out it in `callbackModules/__init__.py` > `from . import statistictables   # TODO: `  and `viewModules/__init__.py` > `from .statsview import statsview_layout`
And in `pagecallbacks.py` we comment out line 28 + 29. Just so that there's no coupling with it.

I'll have to look into how tables work in Dash and I'll see what I can do with it.

**Comment by Anonymous5726221** [comment]
Yeah nah looks like that was it. The app now can run and figures are being correctly displayed.

**Comment by ontracrous** [comment]
I messed around with it some more.
Changed the filter to return masks instead. Didn't work too well otherwise.

Also got rid of a couple of bugs.
Apparently when you're using the `color` argument for plots and there's not enough data in the dataframe because of the filtering it throws an exception. So now the figures are in a try except and will return an empty figure instead if there's no data.

Still on the TODO list:
- datepicker object for start/end date and add them to all the callbacks
- tables are fucked somehow. I tried to comment them back in to see if they worked and `pagecallback.py` complained about `app` being a `NoneType` again. Could be that it doesn't like it because of the methods being called in `statsview_layout`

```
html.Label("Weekly stats."),
statistictables.stat_table_week(),      <--- This one for instance
```

**Comment by Anonymous5726221** [comment]
Cool I'll have a look at the datepicker thingy. Did you have a chance to test the docker-compose stack?

**Comment by Anonymous5726221** [comment]
@ontracrous There is an issue on the map view. When changing the filter the maps disappear and only come back when filters are put back in their initial position.

**Comment by Anonymous5726221** [comment]
I got the CSS to work, I'm gonna try to move the table formatting there to avoid repetition.

**Comment by Anonymous5726221** [comment]
Ok, I'm gonna push what I have for the CSS and let's stop making change for now. I'll review one last time then will deploy that, we'll spend time on CSS once this is live otherwise we'll just keep making change and never deploy it.

**Comment by ontracrous** [comment]
I just added the dark theme to every plot.

**Comment by ontracrous** [comment]
Take your time. And the conflict is so huge because the entire old structure doesn't exist anymore

**Pull request merged**
